- src/DBus.vala
- src/Notification.vala
Mimic the Gala code for creating a notification ID
Fixes #14
> Add a notification id

- src/DBus.vala
- src/Notification.vala
This should eventually be the default action, but for now we just launch the app in a dumb way
>  Launch app when notification clicked

- src/Bubble.vala
> Bubble: escape body text

- src/Bubble.vala
> Bubble: check priority on mouse leave

- data/image-mask.svg
- data/notifications.gresource.xml
- meson.build
- src/Bubble.vala
- src/DBus.vala
- src/Widgets/MaskedImage.vala
Fixes #6 
Fixes showing album art from Music for example. We badge with the app icon so that we can always tell who is sending notifications. This is important for Mail who sends avatars through
> Support image path

- data/application.css
- src/AbstractBubble.vala
- src/Bubble.vala
- src/Confirmation.vala
> Add a close button

- data/meson.build
- data/notifications.gschema.xml
- meson.build
- meson/post_install.py
- src/DBus.vala
> Add do not disturb

- src/AbstractBubble.vala
- src/DBus.vala
Send a signal when notifications are closed that includes their close reason
We need this to know which notifications should be saved in the notifications indicator
> Report notification close reason

- src/Bubble.vala
- src/DBus.vala
We need this when we go to replace
> Move summary fallback inside Bubble

- src/AbstractBubble.vala
- src/DBus.vala
> Allow apps to withdraw notifications

- src/AbstractBubble.vala
- src/Bubble.vala
> Make window non-resizable

- data/application.css
- meson.build
- src/AbstractBubble.vala
> Support prefer dark style

- data/application.css
- src/AbstractBubble.vala
- src/Confirmation.vala
Pull these styles into the system stylesheet instead: https://github.com/elementary/stylesheet/pull/684
> Remove lots of CSS

- src/Bubble.vala
- src/DBus.vala
- src/Notification.vala
Do the absolute least to put actions in the Notification object
> Move actions to Notification

- .github/workflows/main.yml
- meson.build
- src/AbstractBubble.vala
- src/Confirmation.vala
This PR makes notifications dismissible with a swipe gesture.
> Swipe gesture to close notifications

- demo/Application.vala
- demo/MainWindow.vala
- demo/io.elementary.notifications.demo.desktop
- demo/meson.build
- meson.build
Closes https://github.com/elementary/notifications/issues/90
> Add a demo

- demo/Application.vala
- demo/MainWindow.vala
* GObject style
* Remove unnecessary properties
* Clarify "Replaces ID"
* Organize
* Use `attach` for fewer grids
* Correct label case
* Don't use combobox text for logic (that's dangerous if it ever changes or is translated)
* Suggested action button and align
> Demo: misc cleanup

- src/Notification.vala
fixes #26 
Same code that's in notifications indicator
> Notification: sanitize markup

- src/AbstractBubble.vala
> AbstractBubble: Don't accept focus

- src/Bubble.vala
* Avoid manual scaling
* Fall back to `dialog-information`
> Bubble: use FileIcon instead of pixbuf

- data/notifications.appdata.xml.in
> Release 6.0.0

- data/application.css
- src/Bubble.vala
This aims to replace ButtonBox with Box for GTK4 porting. The dimensions of the action buttons are made the same to those buttons inside a buttonbox for similarity
> Replace ButtonBox with Box

- demo/MainWindow.vala
- src/Bubble.vala
- src/DBus.vala
* Reduce some long lines
* Insert some required blank lines
* Fix tabs
Extracted from other PR. Should not cause any functional change.
> Improve style in places

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Reverts elementary/notifications#136
> Revert "Remove old issue templates"

- data/notifications.appdata.xml.in
> AppData: Add stock icon

- src/Notification.vala
> Notification: set icon from icon name

- data/notifications.appdata.xml.in
* Organize in the same order as Music with whitespace between different sections and releases at the end.
* Use one-liner for OARS
* Add missing URLs
* Bump copyright
> Appdata: Reorganize

- src/Notification.vala
Required for https://github.com/elementary/wingpanel-indicator-notifications/pull/252
> Add full markup support

- src/Application.vala
Allow to replace a current running instance of the daemon using the `--gapplication-replace` flag in the command line. This should make easier to test changes without need to kill an running instance before.
> Application: Allow Replacement of Running Instance

- src/DBus.vala
> Block GSD "Automatic suspend" notifications

- data/notifications.appdata.xml.in
New release is required for https://github.com/elementary/wingpanel-indicator-notifications/pull/252
> 7.0.0 Release Notes

- src/Notification.vala
> Fix notifications id

- src/FdoActionGroup.vala
> FdoActionGroup: Update to new Valac

- src/Bubble.vala
> Bubble: use overlay.child

- src/AbstractBubble.vala
- src/Bubble.vala
In the interest of #238 
Doesn't fix keyboard a11y and is probably less than ideal, but at the very least should make notifications announce themselves
> Bubble: set accessible properties

- .github/ISSUE_TEMPLATE/bug_report.yml
Sync these two changes:
- https://github.com/elementary/.github/commit/a38b1369d2f10ce1254c091f4ea0142fb2a24f3c
- https://github.com/elementary/.github/commit/8b0d95f22f9fcfc84c6f96d4ea16875e5b58eb50
> ISSUE_TEMPLATE: Sync with .github repository

- src/CanberraGtk4.vala
Fixes https://github.com/elementary/notifications/issues/263
> Use correct sound theme
