src/DBus.vala

GLib.Notification only requires that the notification title is set. However, our notification design is that we want a title and a body. So, if body is "", we make the body the `summary` and use `app_name` for the title text.
Not sure if the comment is too obvious :man_shrugging:

DBus: Set a fallback title when no body is provided

---

src/DBus.vala

Fixes #12 
* Only create canberra context once and use the same context for every notification
* Move sound sending to a method which makes it easy to disable when we support notification settings in the future
* Look for the notification category and try to auto select an appropriate sound based on that info

DBus: Create a method to send sounds

---

src/DBus.vala
src/Notification.vala

Fixes #7 
Since GLib.Notification only requires a title, we try to get the app icon from AppInfo when it's not supplied.
We need to pass appinfo into the notification because of actions, so might as well do it in this PR as well

DBus: get fallback icon from appinfo

---

src/DBus.vala
src/Notification.vala

Fixes #5 
I set urgent for both high and critical because it seems like `notify-send` (and I'm wondering about `libnotify`) only has "low", "normal", or "critical" and what we get from GLib.NotificationPriority for `notify-send`'s "critical" is GLib's "high"

Set notification priority

---

src/Notification.vala

GNOME Power Manager for example sends `<b>` tags in the body text

Support markup in the body

---

src/Bubble.vala

I approved #19 but I didn't check terminal output. We also have to reset the timeout ID to 0 when doing `Source.remove`.

Reset timeout_id

---

src/Bubble.vala

Reverts elementary/notifications#29
reopens #26 
This breaks markup text like the low power notification

Revert "Bubble: escape body text"

---

src/Bubble.vala
src/DBus.vala

Fixes #1 
Takes only the parts from #15 that are necessary for supporting the default action.
This brings us up to feature parity with the Gala notification server as far as actions go

Support default action

---

src/Bubble.vala

Fixes #31 
Make sure that the body is a maximum of 2 lines and we independently ellipsize each line

Bubble: Max 2 line body and ellipsize

---

src/Bubble.vala

Opening this for discussion. I'd like to hear thoughts about if we should make this the standard code style when assigning multiple properties of an object.
For a single property it may be a bit overkill:
```
var title_label = new Gtk.Label (summary);
title_label.ellipsize = Pango.EllipsizeMode.END;
```
vs
```
var title_label = new Gtk.Label (summary) {
ellipsize = Pango.EllipsizeMode.END
};
```
But from the diff here, it does seem to add clarity. I would also imagine this would help encourage keeping these things all together and organized

Bubble: use alternate syntax for multiple properties

---

meson.build
src/Bubble.vala
src/DBus.vala
src/Notification.vala

It's really a pain to pass around all these arguments and also it gets a bit confusing to see what's going on with all the translating/interpreting we're doing here. This creates a notification object like we use in the indicator to greatly improve legibility and make it a bit easier to get the right properties across the different classes
This also is gonna make actions easier and there's a couple of things that we're not properly doing on replace that will be easy to fix after this

Create notification object

---

src/Confirmation.vala

We're currently relying on the stylesheet to special case progressbars inside of notifications, but this should really just be flat class

Confirmation: Add flat class to Progressbar

---

src/Bubble.vala

This PR adds support for application icons defined as URIs instead of icon names. I tested it with an affected application (Google Chrome) as well as an unaffected one (Music) and both seem to work as expected. Please let me know if I need to make any adjustments.
Closes #119

Handle URIs used for application icons (#119)

---

src/Notification.vala

This PR adds a code change which loads a *.desktop file from `/etc/xdg/autostart` if available. This is needed for daemon processes which are automatically started in the background and are sending notifications to the user.
**Notification displayed before change**
**Notification displayed after change**

Fix #117: Show icons for daemons

---

src/Bubble.vala

Bubble: don't pack action area for default action

---

src/Bubble.vala

Fixes #131. To test:
- send a notification with a long, one-word body like `aaaaaaabbbbbbbcccccccdddddddeeeeeeefffffffggggggg`
- double-check with a more regular notification like `This is a normal, long notification test. Things should wrap at the natural word boundaries as you'd expect.`

Bubble: wrap between characters if needed

---

src/Notification.vala

Discovered while testing GNOME Clocks. If `app_name` and `body` are both blank, we get a missing notification title. Adds a fallback for app_name to check app_info

Notification: get app_name fallback from appinfo

---

demo/MainWindow.vala
src/Bubble.vala
src/Notification.vala

While we don't want apps misrepresenting themselves by removing their own automatically set icon, we can allow them to be more expressive by setting a badge via `Notification.set_icon ()`
* Added some comments so its more clear how what we get from DBus matches GLib.Notification
* If we get an icon name via the `image-path` hint, and its not the app icon name, create a badge icon for it
Looks like:

Add a badge with set_icon

---

src/Bubble.vala
src/Notification.vala

This is all getting pretty complicated and #123 would make it even more complicated. This branch moves more of the image/icon logic to `Notification` so that `Bubble` can be pretty straightforward. It also makes fallbacks more straightforward to implement
* Add a new property `primary_icon`. Notification server clients try to either give us a gicon from appinfo, an icon name, or a path to an icon. All of these can be handled by GIcon, so this lets us set a single property instead of having Bubble try to create an image by null checking several properties
* Add a new property `image`. There are two ways clients could try to set an image: file path or (in the future) image data. This lets `Bubble` check for a single property to see if a `MaskedImage` has been created or not.
* The …

Move Image/Icon logic to Notification class

---

src/AbstractBubble.vala

AbstractButton: Don't propagate events on close button release

---

src/Notification.vala

This reverts commit a6d20d5e825900ca37e54c06a4967c8f658ca70b.
>Please revert this. We shouldn't be loading desktop files from the autostart folder. This folder is *only* for desktop files that should be launched with the session (and they don't even need to be fully formed desktop files). Hence why this isn't in the standard lookup path for `DesktopAppInfo`.
>
>If something (a daemon or otherwise) wants to send notifications, it should install a desktop file to an XDG applications path (e.g. `/usr/share/applications`). If it should be hidden from the applications menu because it's a daemon, use the `NoDisplay` key.
_Originally posted by @davidmhewitt in https://github.com/elementary/notifications/issues/118#issuecomment-841344688_

Revert "Fix #117: Show icons for daemons (#118)"

---

src/AbstractBubble.vala

Since in GTK4, we cannot simply use the `add` command to add widgets to Grid anymore, we should use `attach`.

Replace `add` with `attach` for Grid

---

src/AbstractBubble.vala
src/Application.vala

The settings is valid for the whole executable sono need to watch it per bubble.

Move dark theme handling to the Application class

---

src/Application.vala
src/DBus.vala

- set the `ApplicationFlags.IS_SERVICE` flag so that glib don't try to call activate when running from terminal.
- move gtk and canberra configuration to `GLib.Application.startup ()`, and use
`GLib.Application.application_id` and `GLib.Application.resource_base_path` so we reduce places with an hardcoded app id.
- do all the dbus handing on `GLib.Application.dbus_register`, and only hold when we aquire the `org.freedesktop.Notifications` name.

Application: use startup and dbus_register instead of activate

---

src/AbstractBubble.vala

The headerbar is not used anywhere so it can be removed.

Remove Unused HeaderBar

---

src/DBus.vala

Applications that are not listed in the switchboard are unable to have their notification settings changed. This checks that list and overrides the application id to "Other" if it is not present, allowing them to behave as expected as an "Other" application.

Allow control of unlisted applications.

---

src/AbstractBubble.vala
src/Bubble.vala
src/Confirmation.vala
src/DBus.vala

DRY the rest of the timeout logic that was still done in the subclasses back to the AbstractBubble class. Now the timeout is started when the notification is presented and resulting in longer bubbles. This also changes an possibly unwanted behaviour in the case of urgent notifications getting expired after hovering over them.
While here, also do a little of cleanup and preparation for Gtk4.

AbstractBubble: Handle Timeout internally

---

src/Bubble.vala
src/DBus.vala

remove the `replace()` method and `construct` block in favor of construct the contents widget in one place. we also stop checking if the notification has no action for launching the application, instead we launch it whenever we don't have a default action.
Fixes some cases of #195/#145.
Fixes: #170

Bubble: minor refactor

---

src/DBus.vala
src/Notification.vala

* remove unused bus proxy.
* gsd notification are blocked early and throws instead of return.
* `send_sound()` and sound logic is simplified.
* the check for `X-GNOME-UsesNotification` is done inside the notification class
* `Settings.with_path()` is used instead of `Settings.full()`

Server: Simplifications

---

src/DBus.vala

This got broken in https://github.com/elementary/notifications/pull/201.

Fix block of "Automatic suspend" notifications

---

data/application.css
src/AbstractBubble.vala

Gtk4 Prep
Set margin in CSS so we don't have to explicitly set every margin property

AbstractBubble: set margin in CSS

---

src/Confirmation.vala

When you e.g. change volume, at the beginning it will show an empty progressbar until you press again so that the value changes.

Confirmation: Fix value only showing once it changed

---

src/AbstractBubble.vala

This was overlooked while porting to Gtk4. We have a separate notification window type in X11 so lets just use it. It doesn't make sense to change window type in Gala since we'll probably remove it soon anyways

Set notification window type on X11

---

src/Application.vala
src/DBus.vala

Cherry-picked from https://github.com/elementary/notifications/pull/266

Move Settings object into Application class

---

src/Application.vala
src/DBus.vala

Sound capabilities are not unique for fdo server, so move `send_sounds` method to the Application class

Move send_sound from Server to Application

---

src/AbstractBubble.vala
src/Bubble.vala
src/DBus.vala
src/FdoActionGroup.vala

CloseReason can be used by other backends as well, so lets move it somewhere more appropriate

Move CloseReason to AbstractBubble
